### ISSUE TITLE
MMpool

### ISSUE THREAD

**Issue by colt05** [pooler/cpuminer#101]
Hi.
I'm trying to mine on my VM with MMPool. I signed in, and it was mining fine, then Stratum requested work restart a few times. I went on to MMPool to check MHash/Second and it was 0.
But why? Here are the last few lines of the mining log so far:
    Stratum requested work restart
    thread 0: 483250576 hashes, 8664 khash/s
    thread 0: 519831440 hashes, 8709 khash/s
    thread 0: 522551752 hashes, 8629 khash/s
    Stratum requested work restart
    thread 0: 37294800 hashes, 8722 khash/s
    Stratum requested work restart
    thread 0: 363447088 hashes, 8844 khash/s
    thread 0: 530626160 hashes, 8618 khash/s
    thread 0: 517087152 hashes, 8726 khash/s
    thread 0: 523552424 hashes, 8654 khash/s
    thread 0: 519231016 hashes, 8681 khash/s
Why is this happening?

**Comment by pooler** [comment]
I don't see any issue here.
Pools cannot know your exact speed, they can only estimate it based on how frequently you submit shares. At 8 MH/s, your CPU is simply too slow to find shares frequently enough, so most of the time your speed will be estimated as 0.

**Comment by colt05** [comment]
That makes sense. There are only 8MH/s so if it were higher (say 2.2GH/s) it would work. Thanks.
