### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by colt05** [pooler/cpuminer#103]
Hi. On LabXNow vm, I have tried to use cpuminer with a few different pools, but it just crashes (and doesn't seem to save bash history). As a matter of fact, I have tried it a few times on this VM, but this time it deleted the contents of my Documents folder O.o I have tried ``` --benchmark ```  but that deleted everything. Why is this happening? Thanks.

**Comment by pooler** [comment]
Just tried it myself. It doesn't really "crash", apparently the process is automatically terminated by the system to prevent an abuse of resources. If I limit the miner to 1 thread it manages to run for a few seconds before being terminated.

**Comment by colt05** [comment]
Hm I thought it was because the amount of threads was not detected correctly (Tor detected 64?!). Is there a way to turn that feature off?

**Comment by pooler** [comment]
`/proc/cpuinfo` also reports 64 processors, so that's correct.
You can of course use the `-t` option to change the number of threads, but it's quite obvious that this kind of platform is totally unsuitable for running `minerd`.

**Comment by colt05** [comment]
Ok, but what about the Documents folder? :fearful:

**Comment by pooler** [comment]
That didn't happen to me. And even assuming it did happen to you, it's almost certainly a bug/feature of LabXNow, as `minerd` doesn't directly create or delete files, ever.
