### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by maciekish** [pooler/cpuminer#104]
Hi, can this run on iOS?

**Comment by maciekish** [comment]
If so, can it run kn some pooled kind of manner so that 5 mins of work mean anything?

**Comment by pooler** [comment]
I remember I got cpuminer to compile and run on an iPhone 3G a few years ago, so it is definitely possible. Is it worth it? Only for the learning value. Do not expect it to be anywhere near profitable, especially now that *any* kind of CPU mining is worthless (except for educational and testing purposes).
