### ISSUE TITLE
Set CPU Usage limit?

### ISSUE THREAD

**Issue by sfxworks** [pooler/cpuminer#106]
I love this but I don't want my fan to scream when I run it. I want it running in the background at about 40%. Can you make this possible? I read somewhere you can assign it to a few cores but I'd rather then all distribute evenly among them all.

**Comment by pooler** [comment]
I think this is best left to external tools such as [cpulimit](https://github.com/opsengine/cpulimit) or [Battle Encoder Shirase](http://deztec.jp/x/05/faireal/BES-index.html).

**Comment by sfxworks** [comment]
I guess.
Would be neat so I could use something that wouldn't launch a window. Want to throw this into my application too without frying everyone's processor that installs it.
[New BES site http://mion.faireal.net/BES/]

**Comment by sherifomran** [comment]
is there a similar one for windows?
