### ISSUE TITLE
No url supplied close so fast

### ISSUE THREAD

**Issue by Omardavinci** [pooler/cpuminer#109]
Hi i was trying to run but show me fast this message no url supplied and close so fast. Why what i'm doing wrong?  Thanks in advance.

**Comment by pooler** [comment]
`minerd` is a CLI (command line interface) application, it has no graphical interface. If you don't know how to use the CLI of your operating system, then you almost certainly don't want to run cpuminer, as nowadays its practical uses are limited to stress testing and to the debugging of other mining-related software..
