### ISSUE TITLE
Autogen not working on CentOS 6

### ISSUE THREAD

**Issue by gaffelosked** [pooler/cpuminer#110]
Libcurl version: libcurl 7.51.0
automake (GNU automake) version 1.11.1
autoconf (GNU Autoconf) version 2.69

Code:
configure.ac:132: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2031: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2052: AC_CACHE_CHECK is expanded from...
/usr/share/aclocal/libcurl.m4:38: LIBCURL_CHECK_CONFIG is expanded from...
configure.ac:132: the top level

Tried everything, frustrated as f*ck right now...

**Comment by pooler** [comment]
`autogen.sh` is giving me no errors with autoconf 2.69 and the libcurl.m4 file from curl 7.51.0, so I'd say there's probably something wrong with your setup.

The easy fix is to build cpuminer from tarball.
