### ISSUE TITLE
Segfaults for scrypt on PPC64 Big Endian

### ISSUE THREAD

**Issue by KungFuJesus** [pooler/cpuminer#111]
Builds ok, segfaults very early on.  Can't get a stack trace out of it, possibly for unrelated GDB/Pthread reasons.  

```
adam@g5box ~/cpuminer $ ./minerd -s6 -O xxx.xx:xxxx -o stratum+tcp://usa4.wemineltc.com:3333
[2016-11-20 12:23:03] Binding thread 1 to cpu 1
[2016-11-20 12:23:03] 4 miner threads started, using 'scrypt' algorithm.
[2016-11-20 12:23:03] Starting Stratum on stratum+tcp://usa4.wemineltc.com:3333
[2016-11-20 12:23:03] Binding thread 0 to cpu 0
[2016-11-20 12:23:03] Binding thread 2 to cpu 2
[2016-11-20 12:23:03] Binding thread 3 to cpu 3
Segmentation fault

(gdb) r -s6 -O kungfujesus.g5:passw0rd -o stratum+tcp://usa4.wemineltc.com:3333
Starting program: /home/adam/cpuminer/minerd -s6 -O xxx.xx:xxxx  -o stratum+tcp://usa4.wemineltc.com:3333
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x3fffb78d11a0 (LWP 9394)]
[New Thread 0x3fffb70d11a0 (LWP 9395)]
[New Thread 0x3fffb68d11a0 (LWP 9396)]
[2016-11-20 12:24:02] Starting Stratum on stratum+tcp://usa4.wemineltc.com:3333
[New Thread 0x3fffb60d11a0 (LWP 9397)]
[2016-11-20 12:24:02] Binding thread 0 to cpu 0
[New Thread 0x3fffb58d11a0 (LWP 9398)]
[New Thread 0x3fffb50d11a0 (LWP 9399)]
[2016-11-20 12:24:02] Binding thread 2 to cpu 2
[New Thread 0x3fffb48501a0 (LWP 9400)]
[2016-11-20 12:24:02] 4 miner threads started, using 'scrypt' algorithm.
[2016-11-20 12:24:02] Binding thread 3 to cpu 3
[2016-11-20 12:24:02] Binding thread 1 to cpu 1
[Thread 0x3fffb50d11a0 (LWP 9399) exited]
thread_get_info_callback: cannot get thread info: generic error
```

**Comment by pooler** [comment]
Does SHA-256d work?

**Comment by KungFuJesus** [comment]
Nope:

```
adam@g5box ~/cpuminer $ ./minerd -t4 --benchmark -ascrypt
[2016-11-20 12:55:09] Binding thread 2 to cpu 2
[2016-11-20 12:55:09] Binding thread 3 to cpu 3
[2016-11-20 12:55:09] 4 miner threads started, using 'scrypt' algorithm.
[2016-11-20 12:55:09] Binding thread 0 to cpu 0
[2016-11-20 12:55:09] Binding thread 1 to cpu 1
Segmentation fault
adam@g5box ~/cpuminer $ ./minerd -t4 --benchmark -asha256d
[2016-11-20 12:55:13] Binding thread 1 to cpu 1
Segmentation fault

```

I've been trying to add some fprintf stderr statements just to find the line it's crashing on but it's hard to determine which pthread function it's dying in.  It doesn't seem to even get to the switch to determine which algorithm to use.  In my experience these sorts of issues tend to happen in pthread mutex lock acquisitions (e.g. there's a corner case where the same lock is acquired twice in the same thread).  I've noticed that sometimes the issue will go unnnoticed in x86 but other times in SPARC it will show up and fail in strange ways.  I also noticed a memcmp statement with a statically coded number of bytes -- this may not be advisable unless the structs are packed.

**Comment by pooler** [comment]
Just to rule out the possibility of an issue in the assembly code, could you please try a clean build with `./configure --disable-assembly`?

**Comment by KungFuJesus** [comment]
Interesting, appears to work:

```
adam@g5box ~/cpuminer $ ./minerd -t4 --benchmark -asha256d
[2016-11-20 13:42:19] Binding thread 1 to cpu 1
[2016-11-20 13:42:19] 4 miner threads started, using 'sha256d' algorithm.
[2016-11-20 13:42:19] Binding thread 3 to cpu 3
[2016-11-20 13:42:19] Binding thread 0 to cpu 0
[2016-11-20 13:42:19] Binding thread 2 to cpu 2
^C
adam@g5box ~/cpuminer $ ./minerd -t4 --benchmark -ascrypt
[2016-11-20 13:42:28] Binding thread 1 to cpu 1
[2016-11-20 13:42:28] Binding thread 2 to cpu 2
[2016-11-20 13:42:28] 4 miner threads started, using 'scrypt' algorithm.
[2016-11-20 13:42:28] Binding thread 3 to cpu 3
[2016-11-20 13:42:28] Binding thread 0 to cpu 0
```

So I guess that assembly is not 64 bit compatible for some reason.  Is there any reason it's handcoded assembly as opposed to utilizing a compiler's intrinsics?  The compiler can generate some reasonable machine code with vec_*.

**Comment by pooler** [comment]
This is interesting, because I'm pretty sure I did test the code on an Xserve G5 using Debian/PPC64. Unfortunately I do not have access to that machine at the moment so I cannot double-check.

The reason for the hand-coded assembly is simply that this project aims at squeezing every last drop of performance. Not for practical reasons, of course, since cpuminer is not used for any real mining anymore, but just as a study in optimization for various architectures.
By the way, Altivec instructions are not compiled in by default; instead, a version compatible with earlier PPC CPUs is used (see `README`).

**Comment by KungFuJesus** [comment]
Yeah I added the flag. Haven't had much opportunity to look at it further,
but I did notice that in the core function the lvx instructions are loading
values starting from offset 0 from register 3. Is the 64 bit calling
convention different for PPC maybe? I'm not sure if r3 is a 64 or 32 bit
register.

**Comment by KungFuJesus** [comment]
Hmm actually according this http://refspecs.linuxfoundation.org/ELF/ppc64/PPC-elf64abi.html#PARAM-PASS

That should be right. Very little of that assembly spills anything out of registers, though.

**Comment by KungFuJesus** [comment]
The more I look into it, the weirder it gets.  I commented out the core call to the algorithm (scrypt_core), and it still crashes, despite not actually calling that code.  Disabling assembly when building does not make it crash (and as expected, I get artificially high hash rates, as it's not doing any real work).

**Comment by KungFuJesus** [comment]
The bug is in sha256_transform()'s assembly.  Just have to find where in there it's addressing memory.

**Comment by KungFuJesus** [comment]
Yeah so compiling with the C sha2 implementation but the assembly altivec scrypt implementation worked, so the issue definitely lies somewhere in sha2-ppc.S.  I see a lot of *4's in there, but many of the operands are 4 byte values (uint32_t).  I also made the mistake of running no_macro.pl, which expands all the assembly macros to inflate the code even larger.  

At the very beginning of sha256_transform you're doing an endianness check, and you're using the stack from pointer register to do it.  I'm not entirely sure I understand the mnemonic here, and it's possible you're just using the stack frame pointer register (r1) at the beginning of the function to save you some GPRs later.  But here's a potential source of the issue:

sha256_transform:
_sha256_transform:
    stwu    r1, -72*4(r1)
    cmpwi   0, r5, 0
    stw r13, 2*4(r1)
    stw r14, 3*4(r1)
    stw r15, 4*4(r1)
    stw r16, 5*4(r1)
    
    bne 0, sha256_transform_swap

From what I can understand, this is negatively addressing from the stack from pointer (precisely 72 integer values behind), and then storing the lower order 32 bits of r1 into something.  Perhaps there's some bogus pointer arithmetic going on here?  It's hard for me to tell, I don't quite grasp exactly what that instruction is doing (but likely it's trying to compare some immediate stored value with itself).  Maybe it's unrelated, it could be just moving the stack frame for some stack allocations.

**Comment by KungFuJesus** [comment]
Ahh, reading the stack frame info here made it a bit more clear:

http://refspecs.linuxfoundation.org/ELF/ppc64/PPC-elf64abi.html#AEN369

You're atomically modifying the stack frame (as required).  However, I think you need to use the stdu instruction for 64 bit.

**Comment by pooler** [comment]
Thank you for your research! (By the way, if you are unsure about the semantics of some instruction, I personally find [this page](http://www.ds.ewi.tudelft.nl/vakken/in101/labcourse/instruction-set/) useful.) Unfortunately I haven't looked at this code (or PPC in general) for quite some time so I don't remember the details, I need to take some time to familiarize with it again.

Meanwhile, I managed to get access to that Xserve I mentioned again, but I was unable to reproduce the issue. The miner appears to work fine both with and without Altivec. This system has a PPC970FX CPU and is running Debian 7 ppc64. Would you mind sharing the specs of your machine?

**Comment by KungFuJesus** [comment]
Sure, I have a 2x dual core PPC970MP machine at 2.4GHz.  I can also send
you the binary if need be.  I'm running the latest master in git.  I'm
using GCC 5.4.  It definitely is crashing in the SHA2 portions of the code,
as when I undefine EXTERN_SHA256 and comment out the portions in miner.h
related to enabling the sha256 4 way functions it mines at around 3.4x the
throughput of the purely scalar C code.  On a G4 I have, the hashrate with
the sha portions compiled in the altivec instructions is around 5.5x faster
and works (as a 32 bit binary, of course).

I'm not sure if debian does a 32 bit userland and 64 bit kernel like some
distros would do, but I'm using a pure 64 bit userland environment.  So
it's possible you may need to compile with -m64 to get a 64 bit binary.

**Comment by pooler** [comment]
> I'm not sure if debian does a 32 bit userland and 64 bit kernel like some distros would do, but I'm using a pure 64 bit userland environment.

You were right on the money. Turns out that despite the 64-bit kernel this system has a 32-bit userland. Stupid of me not to check before.
Anyway, after installing multilib support and building a 64-bit libcurl, I finally managed to reproduce the bug perfectly. Now I just need to find some time to look into it. :-)

**Comment by pooler** [comment]
After a brief analysis I think one thing is pretty clear: all pointers need to be upgraded to 64 bits. This will of course require some reordering of the stack, but hopefully it won't be too much work.

**Comment by KungFuJesus** [comment]
Besides the pointer issue, I found what I suspect is the most immediate one.  This document describes the difference between PPC32 and PPC64 assembly:
https://www.ibm.com/developerworks/library/l-ppc/

Especially with regards to jumping to a function label.  They cite the bl instruction actually causing a crash because you're likely jumping to a function descriptor rather than a function address.  They then link to a document containing a simple example.

**Comment by KungFuJesus** [comment]
Also:

> Programs use the 64-bit PowerPC bl instruction to make direct function calls. The bl instruction must be followed by a nop instruction. For PowerOpen compatibility, the nop instruction must be:
> 
>     ori  r0,r0,0

http://refspecs.linuxfoundation.org/ELF/ppc64/PPC-elf64abi.html#FUNC-CALLS

**Comment by pooler** [comment]
Commit 475771d appears to do the trick on my machines. Could you please check it out?

**Comment by KungFuJesus** [comment]
Yep, that did it.  Cool.
