### ISSUE TITLE
error “json-rpc call failed:[-1,”'L' format requires 0 <=number<= 4294967295“,null]” how to solve it?

### ISSUE THREAD

**Issue by qmhedging** [pooler/cpuminer#114]
cpuminer (version 2.4.5 win32) error message “json-rpc call failed:[-1,”'L' format requires 0 <=number<= 4294967295“,null]” how to solve it?

other parameters are "--scrypt -o stratum+tcp://global.wemineltc.com:3333"

on Intel i5 windows 7 platform, thanks.

**Comment by pooler** [comment]
The error is returned by the server in response to a perfectly valid `mining.subscribe`. You should contact the pool, this looks like a bug in their Stratum server implementation.

**Comment by qmhedging** [comment]
Thanks pooler, I'll inform the pool.
