### ISSUE TITLE
segmentation fault when starting with different port 

### ISSUE THREAD

**Issue by cheezuscraizt** [pooler/cpuminer#123]
Hi,

if I start the miner with port 8080 I get a core dump:
```
minerd -o stratum+tcp://litecoinpool.org:8080 -O cheezuscraizt.ubuntu:ubuntu  --threads=5 -D
[2017-06-20 13:29:56] Starting Stratum on stratum+tcp://litecoinpool.org:8080
[2017-06-20 13:29:56] 5 miner threads started, using 'scrypt' algorithm.
[2017-06-20 13:29:56] Stratum session id: 160071aea616b6b5
[2017-06-20 13:29:56] Stratum difficulty set to 1024
Segmentation fault (core dumped)
```
```
 tail -1 kern.log
Jun 20 13:29:56 svwbstst8 kernel: [  860.447381] minerd[6616]: unhandled signal 11 at 00000000775cf8d0 nip 000000003e9bc3cc lr 000000003e9bc394 code 30001
```

It's an Ubuntu 17 build on power8 with ppc64le
```
uname -a
Linux svwbstst8 4.10.0-24-generic #28-Ubuntu SMP Wed Jun 14 08:14:41 UTC 2017 ppc64le ppc64le ppc64le GNU/Linux
```

If I start the miner with port 3333 it won't crash, but cannot connect through the firewall and the connection times out.

What can be the cause of the core dump?

Best Regards

**Comment by pooler** [comment]
I doubt the port has anything to do with the issue, it's probably just that in the second case the miner never starts hashing because it can't connect to the server. You should verify by running in `--benchmark` mode, it should also crash. While you're at it, please check if it also crashes on SHA-256d.
This sounds like some kind of compatibility bug in the PPC assembly code. Did you compile from git master, or from a released tarball?

**Comment by cheezuscraizt** [comment]
Thanks for the quick reply!
The version is compiled from sourceforge, sorry for missing that piece of information.
 ```
minerd --version
cpuminer 2.4.5
 built on Jun 20 2017
 features: PowerPC AltiVec
libcurl/7.52.1 OpenSSL/1.0.2g zlib/1.2.11 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) librtmp/2.3
```
Both Benchmarks (script and sha256d) are crashing.

I can test the git-version on a fresh install if you want. 
Best Regards

**Comment by pooler** [comment]
Yes, please do test the latest git version, I think this may be a duplicate of #111, which was fixed by commit 475771d.

**Comment by cheezuscraizt** [comment]
Hi, 

the git version fixes the problem. Sorry for the duplicate!

Best Regards

**Comment by pooler** [comment]
No worries. It's always nice to hear from people who run cpuminer on anything that isn't x86-based. :)
