### ISSUE TITLE
Building on Ubuntu 16.04

### ISSUE THREAD

**Issue by reppolice** [pooler/cpuminer#125]
Since it took me some effort, the prerequisites from a fresh install:

sudo apt-get install  libcurl4-openssl-dev
sudo apt-get install pkg-config
sudo apt-get install eclipse-cdt-autotools

That last one is overkill, but considering how mysterious errors the absence of pkg-config was giving me, I thought more is not less :)

**Comment by pooler** [comment]
`sudo apt-get install make libcurl4-openssl-dev` should be enough. Add `automake` if you want to build from the git repo. See [here](https://bitcointalk.org/index.php?topic=55038) for a build recipe.
