### ISSUE TITLE
hide password

### ISSUE THREAD

**Issue by ysharoiko** [pooler/cpuminer#128]
When running from console password is opened and can be seen by ps ax 
Moreover if we make bat file we write password in open way. Maybe some hash will look safier.

**Comment by pooler** [comment]
The worker usernames and passwords used for pool mining are not usually sensitive information, as they only allow one to submit shares.
That said, if you need to keep this information secret you can use a configuration file with appropriately set permissions.

**Comment by ysharoiko** [comment]
minerd -o stratum+tcp://ltc.pool.minergate.com:3336 -u email.com -p `cat password.txt`
helped me

**Comment by pooler** [comment]
I'd say a configuration file is a cleaner solution. See `example-cfg.json` for an example.

**Comment by ysharoiko** [comment]
Sure it is. Did not know it has such an option. Thank you.
