### ISSUE TITLE
Warning while building programm

### ISSUE THREAD

**Issue by SokaSok** [pooler/cpuminer#131]
Hi,
I got theese warning as result of make command during the building of cpuminer:

> miner.h:188:58: warning: ‘struct cryptonight_ctx’ declared inside parameter list
   uint32_t max_nonce, unsigned long *hashes_done, struct cryptonight_ctx *persi
                                                          ^
miner.h:188:58: warning: its scope is only this definition or declaration, which      is probably not what you want
cryptonight_aesni.c: In function ‘cryptonight_hash_ctx’:
cryptonight_aesni.c:90:37: warning: passing argument 3 of ‘keccak’ from incompat     ible pointer type [-Wincompatible-pointer-types]
  keccak((const uint8_t *)input, 76, &ctx->state.hs, 200);
                                     ^
In file included from cryptonight_aesni.c:2:0:
cryptonight.h:64:6: note: expected ‘uint8_t * {aka unsigned char *}’ but argumen     t is of type ‘union hash_state *’
 void keccak(const uint8_t *in, int inlen, uint8_t *md, int mdlen);
      ^
cryptonight_aesni.c:94:5: warning: implicit declaration of function ‘memcpy’ [-W     implicit-function-declaration]
     memcpy(ctx->text, ctx->state.init, INIT_SIZE_BYTE);
     ^
cryptonight_aesni.c:94:5: warning: incompatible implicit declaration of built-in      function ‘memcpy’
cryptonight_aesni.c:94:5: note: include ‘<string.h>’ or provide a declaration of      ‘memcpy’
cryptonight_aesni.c:172:18: warning: initialization from incompatible pointer ty     pe [-Wincompatible-pointer-types]
  uint64_t *dst = &ctx->long_state[c[0] & 0x1FFFF0];
                  ^
cryptonight_aesni.c:215:10: warning: passing argument 1 of ‘keccakf’ from incomp     atible pointer type [-Wincompatible-pointer-types]
  keccakf(&ctx->state.hs, 24);
          ^
In file included from cryptonight_aesni.c:2:0:
cryptonight.h:65:6: note: expected ‘uint64_t * {aka long unsigned int *}’ but ar     gument is of type ‘union hash_state *’
 void keccakf(uint64_t st[25], int rounds);

Is there something I have to fix? How can I do it?
Thank a lot to all those who will be patient

**Comment by pooler** [comment]
There is no `keccak` function in this repo.

**Comment by SokaSok** [comment]
where can I find this keccak funct? 
It doesn't find the declaration of memcpy too. Is it the file ruined or could it be becouse of lack of dependencies?

**Comment by pooler** [comment]
It means you must be using a fork of this project. Which of the many forks, I have no idea.

**Comment by jackmawer** [comment]
For this particular fork, you can simply use the binary which was successfully compiled as "minerd" - this warning appears to be safe to ignore.
