### ISSUE TITLE
Bitcoin mining

### ISSUE THREAD

**Issue by MiningIsSienceRight** [pooler/cpuminer#136]
Hey there,

I don't know if I'm right here but I got linked to an issue thread here in the forum and the audience seemed very capable of understanding him and he solved his problem in the end.
So to keep it short:

I tried me a bit in GPU-mining with my GTX 1070 OC 8GB to get some practice in mining and being capable of compare the costs to profitability. So my first try was to mine CannabisCoins - I setup my .bat and it worked more or less in the first try. After a few hours of mining I could see the results in the pool site I registered. CannabisCoin is using x11 algorithm and I used CCMiner for it.

My second try was mining Bitcoins so I needed a Miningtool, which would have that sha256 algorithm implemented. I chose BFGMiner for it. 
The .bat-file looks like this:

bfgminer.exe -S opencl:auto -o stratum+tcp://eu.multipool.us:3332 -u EnForcer90.2 -p x --set-device intensity=9 --auto-fan --auto-gpu --set-device OCL:clock=750-950 --set-device OCL:memclock=300

When I start it, I only come to this steps (even when I start it without OC-settings):

![bfgminer](https://user-images.githubusercontent.com/31521296/29944526-1869e06e-8e9e-11e7-8f95-e2af557bc5af.jpg)

Could anyone help me there? I think it has probably something to do with the difficulty of the blocks and also the amount of 0,91 GH/s seems ridiculously high to me.

I am thankful for any suggesting regarding the solving of the problem and will provide any information which I haven't mentioned yet.

Thanks in advance!

Best regards,

MiningIsScienceRight

**Comment by pooler** [comment]
This is the issue tracker for cpuminer, not a help forum.
