### ISSUE TITLE
libcurl is not usable (required is > 7.15.2. I have 7.52.1)

### ISSUE THREAD

**Issue by mohit-vellanki** [pooler/cpuminer#138]
I am following [this](https://www.dash.org/forum/threads/noob-proof-how-to-install-cpuminer-under-ubuntu-linux.2168/#post-18263) to install and mine Dash on my Ubuntu laptop

> ~/darkcoin-cpuminer-1.3-avx-aes$ ./configure CFLAGS="-O3 -march=native"
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking target system type... x86_64-pc-linux-gnu
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... no
> checking for mawk... mawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether to enable maintainer-specific portions of Makefiles... no
> checking for style of include used by make... GNU
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking dependency style of gcc... gcc3
> checking for gcc option to accept ISO C99... none needed
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking whether gcc needs -traditional... no
> checking dependency style of gcc... gcc3
> checking for ranlib... ranlib
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking sys/endian.h usability... no
> checking sys/endian.h presence... no
> checking for sys/endian.h... no
> checking sys/param.h usability... yes
> checking sys/param.h presence... yes
> checking for sys/param.h... yes
> checking syslog.h usability... yes
> checking syslog.h presence... yes
> checking for syslog.h... yes
> checking for sys/sysctl.h... yes
> checking whether be32dec is declared... no
> checking whether le32dec is declared... no
> checking whether be32enc is declared... no
> checking whether le32enc is declared... no
> checking for size_t... yes
> checking for working alloca.h... yes
> checking for alloca... yes
> checking for getopt_long... yes
> checking whether we can compile AVX code... yes
> checking whether we can compile XOP code... yes
> checking whether we can compile AVX2 code... yes
> checking for json_loads in -ljansson... no
> checking for pthread_create in -lpthread... yes
> checking for gawk... (cached) mawk
> checking for curl-config... /home/mohit/anaconda3/bin/curl-config
> checking for the version of libcurl... 7.52.1
> checking for libcurl >= version 7.15.2... yes
> checking whether libcurl is usable... no
> configure: error: Missing required libcurl >= 7.15.2

`

**Comment by pooler** [comment]
You're in the wrong repo.
