### ISSUE TITLE
libcurl build failure on Mac OSX 10.8.x

### ISSUE THREAD

**Issue by geuis** [pooler/cpuminer#14]
Cloned the git repo. Running into a couple problems.

libcurl isn't being found, and there may be a syntax error in ./configure.

OSX has libcurl 7.24.0 included. Location of the lib is found via the curl-config utility, i.e.:

```
curl-config --libs //-L/usr/local/lib -lcurl -lssl -lcrypto -lldap -lz
```

I'm not terribly familiar with this build system. The only check I find for libcurl is line 5566 of configure, "LIBCURL_CHECK_CONFIG". There's a syntax error here:  

./configure: line 5566: syntax error near unexpected token `,'
./configure: line 5566:`LIBCURL_CHECK_CONFIG(, 7.10.1, ,'

Happy to help further diagnose and test fixes.

**Comment by CHiiLD** [comment]
plz check this url https://www.anintegratedworld.com/to-build-from-source-binary-or-tarball/
current i solved same error!
