### ISSUE TITLE
Lower hash rate with miner compiled from source code 

### ISSUE THREAD

**Issue by mlsBlue** [pooler/cpuminer#141]
Hi everyone, 
For few days now I have a problem and I hope somebody can give me the answer. Are they any particular flags that I need to use during building miner from the source code for Windows? Used LIBCURL="-lcurldll" ./configure CFLAGS="-O3" to configure and make to create .exe file. Because my compiled and builded .exe file produces much lower hash rate then .exe file downloaded externally. My .exe 5-7 kH/s, Binaries .exe 20-25 kH/s. Also is much slower in acceptiong blocks. CPU is Intel i7-7500U, 2.7 GHz, hp laptop.
Thank you in advance.

**Comment by pooler** [comment]
Please post your `config.log`.

**Comment by mlsBlue** [comment]
There is config.log file.
[config.log](https://github.com/pooler/cpuminer/files/1339809/config.log)

**Comment by pooler** [comment]
You compiled for 32-bit x86. Judging from the hash rate you reported, I'm guessing the the binary you downloaded is 64-bit, and that would explain the difference in hash rate.

**Comment by mlsBlue** [comment]
Yes I downloaded 64-bit binaries. Also I downloaded and 32-bit binaries and there is the difference in hash rate. So that is the probable reason for it lower hash rate in my builded miners. Now when I try to build 64-bit version on Windows using MinGW, I get undefined reference errors. I went through Makefile and I saw that some parts are commented for 64-bit version. Errors are in file.
[error64bit.txt](https://github.com/pooler/cpuminer/files/1340751/error64bit.txt)

**Comment by pooler** [comment]
It looks like something was configured incorrectly. Please post the new `config.log`.

**Comment by mlsBlue** [comment]
New config.log.
[config.log](https://github.com/pooler/cpuminer/files/1340934/config.log)

**Comment by pooler** [comment]
It's still using the 32-bit compiler. I don't know how your environment is set up, but shouldn't you be passing something like `--host x86_64-w64-mingw32`?

**Comment by mlsBlue** [comment]
I passed host parameter but the problem is still the same. Now my configure command looks like 
`LIBCURL="-lcurldll" ./configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 CFLAGS="-O3"` but the error still remains. Also the gcc compile command looks like this
` gcc -fno-strict-aliasing -O3   -o minerd.exe minerd-cpu-miner.o minerd-util.o minerd-sha2.o minerd-scrypt.o  minerd-sha2-x64.o minerd-scrypt-x64.o -lcurldll -ljansson -lpthread -lws2_32 ` I have feeling that some lib is missing at the and of the command so linker can't connect it in right way.

**Comment by mlsBlue** [comment]
New config log 
[config.log](https://github.com/pooler/cpuminer/files/1341206/config.log)

**Comment by pooler** [comment]
> I have feeling that some lib is missing at the and of the command so linker can't connect it in right way.

I don't think this has anything to do with libraries. My guess is that the code in the two assembly files is being skipped (as instructed) because the compiler doesn't define `__x86_64__`, and if that's the case it must be compiling for 32-bit x86.

**Comment by mlsBlue** [comment]
I tried with several different ways to define compiler for 64-bit. Is there any place where I need to look up in Makefile for compiler definition, just to check if I am doing things right? Thank you for all informations.

**Comment by pooler** [comment]
Sorry, my experience with MinGW (and Windows in general) is rather limited, and I don't currently have time to investigate.

**Comment by mlsBlue** [comment]
Finally I've sorted everything out. Problem was I used MinGW32 whole time, after installing MinGW64 and all dependecies everything is working as expected. Thank you for your help, eventually the problem was with compiler like you guessed.
