### ISSUE TITLE
C compiler cannot create executables 

### ISSUE THREAD

**Issue by syrius01** [pooler/cpuminer#142]
Hi,

I'm getting this error msg when trying to ./build.sh the cpuminer:

checking for C compiler default output file name...
configure: error: in `/home/syrius/cpuminer-multi-1.0.9-multi':
configure: error: C compiler cannot create executables
See `config.log' for more details.
/bin/sh ./config.status --recheck
/bin/sh: ./config.status: Arquivo ou diretório não encontrado
make: ** [config.status] Erro 127
strip: 'cpuminer': No such file

I'm running on CentOS release 6.6 (Final). GCC is installed.

**Comment by pooler** [comment]
> cpuminer-multi

You're in the wrong repo.
