### ISSUE TITLE
minerd: Uunknown protocol

### ISSUE THREAD

**Issue by mafianekcek** [pooler/cpuminer#143]
Hello, when i want to use command: 
minerd -o startum+tcp://bcc.suprnova.cc:3333 ....... ::
minerd: unknown protocol -- 'startum+tcp://bcc.suprnova.cc:3333'
try minerd --help for more information...
Can somebody help me?

**Comment by pallas1** [comment]
Startum?

**Comment by mafianekcek** [comment]
Yes, i am using this tutorial:
https://youtu.be/CD417Ta4GlQ

**Comment by pooler** [comment]
It's `stratum`, not `startum`.
And this is an issue tracker, not a help forum.
