### ISSUE TITLE
Set difficulty on scrypt

### ISSUE THREAD

**Issue by CitoplasmaX** [pooler/cpuminer#145]
How it set difficulty on scrypt? by default is 128 when i am mining dogecoins.

**Comment by pooler** [comment]
The difficulty is set by the server, not by the client.

**Comment by CitoplasmaX** [comment]
Then why with this software don't change difficuty while other workers yes?

**Comment by CitoplasmaX** [comment]
Ok, my difficuty hav changed now but take much time whilr others worker not
