### ISSUE TITLE
About missing the dummy  and flag  fields in the coinbase when enable segwit.

### ISSUE THREAD

**Issue by dungeonsnd** [pooler/cpuminer#148]
From Bitcoin Core's primitive/transaction.h:
https://github.com/bitcoin/bitcoin/blob/v0.13.1rc2/src/primitives/transaction.h#L275

/**
 * Basic transaction serialization format:
 * - int32_t nVersion
 * - std::vector<CTxIn> vin
 * - std::vector<CTxOut> vout
 * - uint32_t nLockTime
 *
 * Extended transaction serialization format:
 * - int32_t nVersion
 * - unsigned char dummy = 0x00
 * - unsigned char flags (!= 0)
 * - std::vector<CTxIn> vin
 * - std::vector<CTxOut> vout
 * - if (flags & 1):
 *   - CTxWitness wit;
 * - uint32_t nLockTime
 */

And from your code:
https://github.com/pooler/cpuminer/blob/master/cpu-miner.c#L466

I found that maybe you haven't add the dummy  and flag  fields when enable segwit.  Why?
Thanks a lot.

**Comment by pooler** [comment]
The coinbase transaction does not use the extended serialization format.

**Comment by dungeonsnd** [comment]
Thanks for answering.

But i've checked the newly block's coinbase data, e.g. : 

https://blockchain.info/zh-cn/tx/95480f90a413e64fd73482c0e81c538b1a6e7d27f4c4e96101e3ecb828d8671f

And the raw coinbase data for the tx from 
https://chainquery.com/bitcoin-api/getrawtransaction/95480f90a413e64fd73482c0e81c538b1a6e7d27f4c4e96101e3ecb828d8671f/0

is : **010000000001010000000000000000000000000000000000000000000000000000000000000000ffffffff5d03f48607244d696e656420627920416e74506f6f6c332f4542312f4144362f4e59412f49205a0003c1fabe6d6de73f887b141ddd000b6a82f2305c02b9f70b03928a96a504814524ce3b8277050400000000000000552a000056050200ffffffff02d01cd84d000000001976a914a93185189b82d0649c64eafbdcf75870d36219af88ac0000000000000000266a24aa21a9ede3ee002019f3a34fed687a467702b7af9cb5c739e75f09eb234a2c898c90e2c70120000000000000000000000000000000000000000000000000000000000000000000000000**

And maybe it exactly has the segwit fields
# version
01000000
# segwit dummy and flag
0001
# in-counter
01
# input[0] prev hash
0000000000000000000000000000000000000000000000000000000000000000
# input[0] prev seqnum
ffffffff
....

**Comment by pooler** [comment]
What I meant is that *cpuminer* does not use the extended serialization format for the coinbase transaction, because as far as I know the basic serialization format is just fine in this case. If you know of any documentation stating that the extended format should be used, please let me know.

**Comment by dungeonsnd** [comment]
Okay, understood.
Thanks.

**Comment by salmanfarisk** [comment]
Hi...
I try to mine segwit transaction using cpuminer. But not confirming segwit transactions. Actually the cpuminer is support segwit transaction.....???

(Sorry for asking the question on closed issue)
