### ISSUE TITLE
Artful Support

### ISSUE THREAD

**Issue by martiankidd** [pooler/cpuminer#149]
"./configure" command on Ubuntu artful throws an serror saying my curl version isn't high enough; even though it is.

![screenshot from 2017-12-01 03-57-57](https://user-images.githubusercontent.com/8162547/33467364-f10d0032-d64b-11e7-88ed-0ba88438158a.png)

**Comment by pooler** [comment]
Are you trying to build from the git repo or from an official tarball?

At any rate, make sure the development package for libcurl is installed. Try `sudo apt-get install libcurl4-openssl-dev`.

**Comment by martiankidd** [comment]
Was installing from the git repo but I rectified the problem by going to an older version.

All the dependencies were installed and updated. Thanks for the assistance; however I still don't know what was/is the cause of the issue

**Comment by pooler** [comment]
For what it's worth, I just tried building on a fresh install of Ubuntu 17.10 and had no issue whatsoever.
```
sudo apt-get install build-essential automake libcurl4-openssl-dev
git clone https://github.com/pooler/cpuminer
cd cpuminer
./autogen.sh
./configure
make
```
