### ISSUE TITLE
Scrypt not starting..

### ISSUE THREAD

**Issue by venigo** [pooler/cpuminer#151]
Hi all,

I installed the lastest 2.5 version. But when using -a scrypt it is starting @ cryptonight.

Log:

> 
> config.status: creating compat/Makefile
> config.status: creating compat/jansson/Makefile
> config.status: creating cpuminer-config.h
> config.status: executing depfiles commands
> xxx@xxx:~/cpum/cpuminer/cpuminer-2.5.0/cpuminer$ make
> make  all-recursive
> make[1]: Map '/home/global/cpum/cpuminer/cpuminer-2.5.0/cpuminer' wordt binnengegaan
> Making all in compat
> make[2]: Map '/home/global/cpum/cpuminer/cpuminer-2.5.0/cpuminer/compat' wordt binnengegaan
> make[3]: Map '/home/global/cpum/cpuminer/cpuminer-2.5.0/cpuminer/compat' wordt binnengegaan
> make[3]: Er hoeft niets gedaan te worden voor 'all-am'.
> make[3]: Map '/home/global/cpum/cpuminer/cpuminer-2.5.0/cpuminer/compat' wordt verlaten
> make[2]: Map '/home/global/cpum/cpuminer/cpuminer-2.5.0/cpuminer/compat' wordt verlaten
> make[2]: Map '/home/global/cpum/cpuminer/cpuminer-2.5.0/cpuminer' wordt binnengegaan
> gcc -DHAVE_CONFIG_H -I.   -pthread  -fno-strict-aliasing -O3 -MT minerd-cpu-miner.o -MD -MP -MF .deps/minerd-cpu-miner.Tpo -c -o minerd-cpu-miner.o `test -f 'cpu-miner.c'                           || echo './'`cpu-miner.c
> mv -f .deps/minerd-cpu-miner.Tpo .deps/minerd-cpu-miner.Po
> gcc -DHAVE_CONFIG_H -I.   -pthread  -fno-strict-aliasing -O3 -MT minerd-util.o -MD -MP -MF .deps/minerd-util.Tpo -c -o minerd-util.o `test -f 'util.c' || echo './'`util.c
> mv -f .deps/minerd-util.Tpo .deps/minerd-util.Po
> gcc -DHAVE_CONFIG_H -I.   -pthread  -fno-strict-aliasing -O3 -MT minerd-sha2.o -MD -MP -MF .deps/minerd-sha2.Tpo -c -o minerd-sha2.o `test -f 'sha2.c' || echo './'`sha2.c
> mv -f .deps/minerd-sha2.Tpo .deps/minerd-sha2.Po
> gcc -DHAVE_CONFIG_H -I.   -pthread  -fno-strict-aliasing -O3 -MT minerd-scrypt.o -MD -MP -MF .deps/minerd-scrypt.Tpo -c -o minerd-scrypt.o `test -f 'scrypt.c' || echo './'                          `scrypt.c
> mv -f .deps/minerd-scrypt.Tpo .deps/minerd-scrypt.Po
> gcc -DHAVE_CONFIG_H -I.   -pthread   -O3 -MT minerd-sha2-x64.o -MD -MP -MF .deps/minerd-sha2-x64.Tpo -c -o minerd-sha2-x64.o `test -f 'sha2-x64.S' || echo './'`sha2-x64.S
> mv -f .deps/minerd-sha2-x64.Tpo .deps/minerd-sha2-x64.Po
> gcc -DHAVE_CONFIG_H -I.   -pthread   -O3 -MT minerd-scrypt-x64.o -MD -MP -MF .deps/minerd-scrypt-x64.Tpo -c -o minerd-scrypt-x64.o `test -f 'scrypt-x64.S' || echo './'`scr                          ypt-x64.S
> mv -f .deps/minerd-scrypt-x64.Tpo .deps/minerd-scrypt-x64.Po
> gcc -fno-strict-aliasing -O3 -pthread  -o minerd minerd-cpu-miner.o minerd-util.o minerd-sha2.o minerd-scrypt.o  minerd-sha2-x64.o minerd-scrypt-x64.o   -L/usr/lib/x86_64-                          linux-gnu -lcurl -ljansson -lpthread
> make[2]: Map '/home/global/cpum/cpuminer/cpuminer-2.5.0/cpuminer' wordt verlaten
> make[1]: Map '/home/global/cpum/cpuminer/cpuminer-2.5.0/cpuminer' wordt verlaten
> xxx@xxx:~/cpum/cpuminer/cpuminer-2.5.0/cpuminer$ minerd -a scrypt
> [2017-12-05 13:07:59] I go faster as root.
> [2017-12-05 13:07:59] Using JSON-RPC 2.0
> minerd: no URL supplied
> Try `minerd --help' for more information.
> xxx@xxx:~/cpum/cpuminer/cpuminer-2.5.0/cpuminer$ sudo minerd -a scrypt -t 6 -s 4 -o stratum+tcp://stratum.aikapool.com:7938 -u vxxxx -p xxxxxx
> [2017-12-05 13:08:11] Using JSON-RPC 2.0
> [2017-12-05 13:08:11] Starting Stratum on stratum+tcp://stratum.aikapool.com:7938
> [2017-12-05 13:08:11] 6 miner threads started, using 'cryptonight' algorithm.
> [2017-12-05 13:08:11] stratum_recv_line failed
> [2017-12-05 13:08:11] ...retry after 10 seconds
> [2017-12-05 13:08:21] stratum_recv_line failed
> [2017-12-05 13:08:21] ...retry after 10 seconds
> ^C
> xxx@xxx:~/cpum/cpuminer/cpuminer-2.5.0/cpuminer$
>

**Comment by pooler** [comment]
> cryptonight

You're in the wrong repo.
