### ISSUE TITLE
Monero Support

### ISSUE THREAD

**Issue by sfxworks** [pooler/cpuminer#156]
Whats the plan to support Monero? Claymore's does but it doesn't allow for commercial use... https://github.com/nanopool/Claymore-XMR-CPU-Miner

**Comment by sfxworks** [comment]
https://github.com/tpruvot/cpuminer-multi I see a fork

**Comment by pooler** [comment]
I made a decision to only support SHA-256d and scrypt in this repo, at least for the time being.
