### ISSUE TITLE
configure.ac:124: error: possibly undefined macro: AC_MSG_ERROR

### ISSUE THREAD

**Issue by Wayho** [pooler/cpuminer#162]
Q:
$ ./autogen.sh
configure.ac:13: installing './compile'
configure.ac:4: installing './config.guess'
configure.ac:4: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing './depcomp'
configure.ac:124: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
A:
$ LANG=C LC_CTYPE=C ./autogen.sh

**Comment by pooler** [comment]
That error is usually caused by the development package for libcurl missing. (See e.g. #74.)

Your solution appears to be specific to an issue with your setup, so I'd like to ask if you could provide more details.

**Comment by xovertheyearsx** [comment]
I had the same issue. Installing libcurl-dev solved it for me.
