### ISSUE TITLE
Answer of error: possibly undefined macro: AC_MSG_ERROR

### ISSUE THREAD

**Issue by Wayho** [pooler/cpuminer#163]
From here
http://www.datazx.cn/windowsyingyongchengxujianrong/201607505.html

Q: autogen.sh dies with "error: possibly undefined macro: AC_MSG_ERROR".
Q: configure chokes on something like "LIBCURL_CHECK_CONFIG(, 7.15.2, ,'".
A: Make sure you have installed the development package for libcurl. If you have and you're still getting the error when compiling from git, try compiling from tarball instead.

**Comment by pooler** [comment]
What you linked to is a copy of the official FAQ, which is linked in README.
