### ISSUE TITLE
Core i3 Processor problems

### ISSUE THREAD

**Issue by kilitary** [pooler/cpuminer#167]
Hello,

Processor is throttling down when cpuminer is run. Initial speed is 3.7GHZ, but when cpuminer is running it slow downs to 2.8GHZ. This is undesirable effect.

Cpu: Intel Core i3 4170, Haswell.
Package: Socket 1150 LGA
Tech: 22nm

I am running cpuminer (ver 3.8.1.1) with this params: 
cpuminer-avx2.exe -a lyra2zoin -o stratum+tcp://zoin.netabuse.net:3000 -u xxx.xxx-p xxx -D -t 1 -P

**Comment by pooler** [comment]
Wrong repo, closing.

**Comment by kilitary** [comment]
sry
