### ISSUE TITLE
stratum_recv_line failed / Stratum connection interrupted

### ISSUE THREAD

**Issue by RajuWebDeveloper** [pooler/cpuminer#169]
Help me, please.
**# For stratum_recv_line failed / Stratum connection interrupted**

How to solve this issue?
![eobot cpu mining problem](https://user-images.githubusercontent.com/37479816/40582746-aed09da6-61a0-11e8-89de-47e24f506d0f.png)

**Comment by pooler** [comment]
Wrong repo, closing.

**Comment by RajuWebDeveloper** [comment]
Help me, please
