### ISSUE TITLE
Mining in French , BCH ( FuckEnglishShit)

### ISSUE THREAD

**Issue by Plinux1** [pooler/cpuminer#170]
Bojour
Qui aurait les bonne. Configuration pour Mining sous Linux !!

Car ici chez les Manchots, Des 2 termes , sont que des  Faux Q et Flèmard qui ne pense qu' à leur Q !!! YesFuckEnglish
Oui 2 ans que me fait chose à traduire vos Idioserie 

Salut
Qui en french 

FuckAllLanguage 

BitcoinFrench@Telegram  or geek0 or miningfr. ALL FRENCH

**Comment by pooler** [comment]
This is an issue tracker, not a help forum. Closing.

**Comment by LissieTilbrook** [comment]
@Plinux1.... @pooler is right. Not a help forum. And if you have a problem with English, and you want the application translated to French, why don't **you** download the source and localize it yourself?

Not to sound condescending. But your attitude, @Plinux1, is despicable.

**Comment by Plinux1** [comment]
Bla, bla, bla
FuckSpeekOnlyEnglishShit comme cela Tu aime ???


Ciao

Vous êtes pas de geek, ha cela non !!

Investments & Mining. Bitcoin & Cryptocoins / 21.06.2018

👌 Mining free for computer via browsers or via Android application. Easy
way for #bitcoin Mining! Invite your friends, family and associates by your
personal link ( 10 level referral) and make many times more money! Get more
than 1 BTC! Develop the network http://bit.ly/2tHNM3P

👍 Best way to invest cryptocurrency. The crypto currency market is
unstable, Secure your investments and earn 1% of profit every workday. Real
estate is the most reliable way to save money and increase it ! You can
earn without investing. Complete the tasks from WLS and get our tokens,
which generate daily profit for you http://bit.ly/2tlwDgu

👉Get your daily passive income by investing in CryptoLux! CLX Trading.
Gain profit by buying and selling of CLX coins. Crypto Trading. Up to 45%
return each month on your Cryptocurrency investment👍 Today's
interest 💎 1.49% http://bit.ly/2JYPh4V

👉KuCoin - Bitcoin Exchange: Bitcoin, Ethereum, Litecoin, KCS , ...
http://bit.ly/2K2OYpp

👍 Phoneum is a #decentralized #cryptocurrency that operates only on mobile
devices via app, empowered by custom #blockchain #technology . The
#TokenSale starts on June 27, 2018 #Airdrop. #mining only Via Phone and
Tablets ( #android & #iPhone ) http://bit.ly/2yrrRDX

👍CoinEx - The Global Digital Coin Exchange http://bit.ly/2txFUCf


👍 Mining Bitcoin & cryptocurrency. Cloud, investments..

1) MinerGate, Mining Cryptocurrency, GUI miner and Mining Pool. (2 Years of
activity) Easy Software for Windows, Ubuntu, Fedora, Android and Mac:
Mining Ethereum, Bitcoin, Litecoin, Bitcoin Gold, Monero,.. mining pool. +
Mobile mining + Investments Cloud Mining Bitcoin, Ether,..
https://minergate.com/a/a24f5f4d22f5a31bea0605ab

2) Mining Bitcoin, Ether, Dash, ZEC (2 Years of activity)
https://hashflare.io/r/79D39AEF

3) Mining Cryptocurrency, Eobot New 10 year contract (2 years of activity)
https://www.eobot.com/new.aspx?referid=483868

4) START Bitcoin Mining. We make industrial mining accessible for everyone.
You get access to the newest and most advanced technologies in the
industry, provided by the leading companies. (1 Year 1/2 activity)
https://hashing24.com/?rid=53616c7465645f5f44fdec737bdfd96a57e1c0cd08f100e4

👌 Mobile Mining
1) ELECTRONEUM. The mobile mining cryptocurrency. Secure and private. App
based mobile mining. Provide a digital payment solution to the developing
world. To earn 1% more, add one code: 4A5EF3
https://electroneum.com

2) New! Mining only via smartphones and tablets! + ICO starts on June 21,
2018. AirDrop. Concour👌 Android and iPhone 👌
https://crowdsale.phoneum.io/?ref=56150b41


👌Wallet Bitcoin, Litecoin, Dollars, ..

1) Coinpayments. Payment Processor | FREE Multi-Coin Wallet. Payment
gateway providing buy now buttons, shopping carts, and more to accept
Bitcoin, Litecoin, and other cryptocurrencies/altcoins on your
website/online store. Invite Friends
https://www.coinpayments.net/index.php?ref=ab53b62bb017d3aa6420b2bc6810ce0f

2) CryptoPay, (2 years of activity) Wallet Bitcoin & Litecoin. Buy Bitcoins
& Litecoin with your bank card. Deposits and withdrawals from Cryptopay are
simple, fast and free. You can send us money from any of the 26 countries
within the SEPA zone https://cryptopay.me/join/e9970f3f

3) Wallet Bitcoin. It's the best cryptocurrency payment center ever, and at
no extra cost! Use this link to get free maps. You'll thank me later 😉
https://links.wirexapp.com/MpmB/4bTIQcutbK?action=affiliate-register&code=BAmvp8d6SU_kHx8LnPGYFQ

4) Bsave, (2 years of activity) Earn ~3% APR on your Bitcoins in a
zero/negative interest rate world economy
https://go.referralcandy.com/share/VSG4KNH


👍Trade/ Trade crypto/ Trade Automatic, copie / Exchange

1) You can copy the best Trade, member traders! So that you win too! Chats,
TV, Nagacoin, Multi Languages... Join the social trading revolution with
me! https://referral.swipestox.com/code=iepf9o

2) Kucoin - The most advanced cryptocurrency exchange to buy and sell
Bitcoin, Ethereum, Litecoin, Monero, ZCash, DigitalNote, Ardor, Kcs
https://www.kucoin.com/#/?r=E5JC3b

3) Trade cryptocurrency https://www.binance.com/?ref=12516258

👋and Exchange
1) Changelly , Bitcoin, Ethereum, Monero, Ripple, Litecoin, Dash,
cryptocurrency exchange https://changelly.com/?ref_id=76bf31763fb6

2) Auto-Exchange feature on ALFAcashier allows you to make quick
CryptoCurrency exchange automatically. You can automatically exchange
CryptoCurrency to funds either into electronic wallet or into bank account
https://www.alfacashier.com/r/2f78c14e

3) CEX, buy and sell Bitcoin. Bitcoin Exchange. Bitcoin Trading
http://bit.ly/2yp2GfN

4) HitBtc, The most advanced cryptocurrency exchange
https://hitbtc.com/?ref_id=5a3633e6307dc

5) The Cryptopia exchange is a powerful currency trading platform. Deposit,
trade, and withdraw Bitcoin, Litecoin, and over 400 other crypto currencies
https://www.cryptopia.co.nz/Register?referrer=Plinux


👌News👍
1) Mining only via phones and tablets! + ICO starts on June 21, 2018. +
Airdrop + Concours. Mobile mining👍 Android and iPhone 👌 Excellent
applications https://crowdsale.phoneum.io/?ref=56150b41

2) Swisscoin, Giracoin, Girauno. Wallet and Mining. Already 7 months of
activity! Investment Mining https://portal.giracoin.com/subscribe/riricoin

3) Automating the World of Cryptocurrency. Dropil, A platform that does the
work for you. Our platform provides you with autonomous tools that simplify
your cryptocurrency analysis, trading, and storage. Autonomous Trading
https://dex.dropil.com/signup?aff=khnGf64ViUqB7pfaR26PNMYpPICOhn


⚠☣ Investments ! ! DANGER ??!!
+ Lending, Volatility software interest up to 48% per month
https://homeblockcoin.com/cjzsliiz
+ Singal trade + lending https://exacoin.co/ref/riricoin
+ Lending https://sficoin.co/ref/riricoin
+ Lending https://ucoincash.co/ref/riricoin
+ Legendcoin https://legendcoin.co/?ref=vazaf
+ First Payment Gateway using Gold backed cryptocurrency
https://www.puregold.io/register?r=fafae492
+ DavorCoin is a new cryptocurrency that aims to become the best
alternative to current popular items such as Bitcoin and Ethereum
https://davor.io/Account/Registration?r=9FB35B


🆓 Crypto 🆓
1) Claim free Bitcoin and Dogecoin
https://freebitco.in/?r=2949201
http://freedoge.co.in/?r=641935

2) Sign up for free daily tokens. Spend them on a range of products or
#hodl them for a rainy day! For each friend you refer you will receive 500
Swifts. + New ICO https://www.swiftdemand.com/?referred_by=riricoin


👍 Website Amateur but honest ! 👌
🏁 https://www.twitter.com/geek0plinux
🏁 https://www.facebook.com/Bitcoin5800
🏁 https://www.cryptomonnais.com

🆕️ Crypto en Français www.facebook.com/BitcoinEnFrench


✊ Contact only via Telegram: BitcoinFrench

Skype: pascalmdk 👋👋👋

**Comment by mehmetkose** [comment]
grew up and come again, dipshit
