### ISSUE TITLE
X13 Not compatible with BitcoinDiamond X13BCD

### ISSUE THREAD

**Issue by juanpc2018** [pooler/cpuminer#171]
using the http://zentec.ddns.net:8090/workers
or https://www.vvpool.com/currency/bitcoin-diamond

cpu-miner has Rejected Shares in zentec,
Rejected Reason: Low Difficulty Share.

in vvpool Rejected Reason: high-hash

using the ccminer -a bcd gpu miner the zentec pool works,
http://blog.vvpool.com/tutorial_en/bcd_en.html

something about Amd Card Not suitable "low hash rate", vs. Nvidia card.
https://pan.baidu.com/s/1mjVtHPY
code：07mp

http://btcd.io/#/download
https://github.com/alexis78/ccminer
https://github.com/eveybcd/gpu-miner
https://github.com/eveybcd/x13bcd_hash
https://github.com/eveybcd/stratum-mining
https://github.com/jgarzik/cpuminer/releases
https://github.com/pooler/cpuminer/releases
https://github.com/JayDDee/cpuminer-opt/releases
https://github.com/tpruvot/cpuminer-multi/releases
https://github.com/lucasjones/cpuminer-multi/releases
https://github.com/BeastPool/cpuminer-argon2d/issues
https://bitcointalk.org/index.php?topic=2448356.msg40760017#msg40760017

**Comment by pooler** [comment]
Wrong repo, closing.
