### ISSUE TITLE
stratum_recv_line failed stratum connection interrupted

### ISSUE THREAD

**Issue by WhiteRedWolf** [pooler/cpuminer#176]
I have been using cpuminer on my laptop (i know that its not profitable but i have the same issue on my main pc) I have been having this issue (both on my main i7 cpu and on my atom cpu) after it tries to find a share it just writes me stratum_recv_line failed stratum connection interrupted, i dont know if its because of the pool (zpool.ca) but i still dont know how to fix it. Both my i7 and my atom have the same issue on the same pool using the same miner

**Comment by pooler** [comment]
That error message normally indicates that the server interrupted the connection. This is likely to happen in the case of CPU mining, as shares are submitted infrequently and many servers drop a connection after some time without a share submission. If you want to be sure you will have to ask the server operator. I doubt this is a client issue, so I'm closing the ticket. Feel free to reopen it if you have reason to believe the client is misbehaving.
