### ISSUE TITLE
cpu miner giving issue 

### ISSUE THREAD

**Issue by awaissakhi11** [pooler/cpuminer#178]
HTTP request failed: Operation timed out after 30001 milliseconds with 0 bytes received

**Comment by pooler** [comment]
Please provide more information and state why you think this is a client-side problem rather than a server-side one.

**Comment by awaissakhi11** [comment]
recently i create one new coin and now i want mining and in my coin there is nothing like mining build in mining software so i am suing cpu miner can you guide me how i can set pool and network so i can mine my coin thank you

**Comment by pooler** [comment]
Sorry, this is not a support forum. Closing.
