### ISSUE TITLE
Question : Are nonce values random?

### ISSUE THREAD

**Issue by SHlNOBI** [pooler/cpuminer#183]
I'm mining on regtest. The target is "7fffff0000000000000000000000000000000000000000000000000000000000". The nonce value of the latest block is way much higher than the cpus hash rate. How  to  specify the nonce value to go from  zero?

Thank you for  your time.

**Comment by SHlNOBI** [comment]
Example of block:

`{
  "hash": "46798d5afb788ef42a32ee3f9966910580ca153525b0ad392de3c9c02286e517",
  "confirmations": 1,
  "strippedsize": 225,
  "size": 261,
  "weight": 936,
  "height": 3264,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "c01f1d9f6e3c7bf7bf13f521146aec3bf81ac77616f87b8753bfcc29dcc1a5e9",
  "tx": [
    "c01f1d9f6e3c7bf7bf13f521146aec3bf81ac77616f87b8753bfcc29dcc1a5e9"
  ],
  "time": 1563114081,
  "mediantime": 1563114080,
  **"nonce": 67108864,**
  "bits": "207fffff",
  "difficulty": 4.656542373906925e-10,
  "chainwork": "0000000000000000000000000000000000000000000000000000000000001982",
  "nTx": 1,
  "previousblockhash": "3f6c9e2e105b634faff9011e59e2b83bbb1fefa0acbf1a0db23c2fb110c2ed99"
}`

**Comment by pooler** [comment]
Nonce values are tried sequentially, with each thread checking a different range. I'm not totally sure I understand your question, but the nonce value does start from zero on the first thread.

**Comment by SHlNOBI** [comment]
Thank you.

I would like to try small  range of  nonce values because  i'm on  regtest. How to specify max nonce  in the code?

**Comment by pooler** [comment]
This is the nonce value to start from:
https://github.com/pooler/cpuminer/blob/f9ef30f0b2b2300dd3f2a80edbfd9c37f0182ead/cpu-miner.c#L1179
And this is the last value to check:
https://github.com/pooler/cpuminer/blob/f9ef30f0b2b2300dd3f2a80edbfd9c37f0182ead/cpu-miner.c#L1112

**Comment by SHlNOBI** [comment]
Than you very much for your  help and time.
