### ISSUE TITLE
Segmentation fault appears in aarch64 android termux

### ISSUE THREAD

**Issue by harieamjari** [pooler/cpuminer#186]
While I successfully builded this in an android (armv71-unknown-linux-gnueabi) and worked successfully when tried connecting to a pool, the other android don't work.

Well, when trying start mining, after it print all the thread binding (overall thread 0-7), its next output is segmentation fault. That's all I know.

One thing also is that compiling this in armv71 is much more easier, though I needed to manually add -llog to LDFLAGS in the makefile.

On the aarch64, I need to manully remove the '#' in JANSSON_INCLUDES.

**Comment by harieamjari** [comment]
If you need more details then I could probably try to find what's the problem and you're going to solve it. (Please no, im lazy)

**Comment by pooler** [comment]
I just tried building in Termux with Clang on an AArch64 tablet running Android 9 (aarch64-unknown-linux-gnu). I did not run into any problem and didn't have to tweak a thing. The miner built just fine after simply running configure and make. I could connect to a pool and it seemed to be mining with no issue.

I am closing this, but feel free to reopen if you can provide a full list of steps to reproduce the issue, including the whole setup of the Termux environment.
