### ISSUE TITLE
random nonce

### ISSUE THREAD

**Issue by letechi123** [pooler/cpuminer#191]
Hi,

Is there a way to change the nonce from incrementing sequentially to just doing it randomly ???
so something like this nonce = random.randint(0, max) ??? 

Thanks

**Comment by h2o10** [comment]
this might help #183

**Comment by letechi123** [comment]
i saw your question, but im just wanting it to randomly just generate a nonce non stop, instead of incrementing...

if that makes sense ?
so basically just a random one every time instead of incrementing on previous one

**Comment by letechi123** [comment]
did you happen to look for the same thing ? or was yours sorted?? and do you know if the owner is still around ?

**Comment by h2o10** [comment]
my issue was sorted. Owner is not active that much. you'll get reply in couple of days.

**Comment by letechi123** [comment]
yeah, aslong as he still check it every few days, all good.. thank you been a great help =)

**Comment by pooler** [comment]
It's certainly possible to alter the code to use random nonces, but why would you want that?

**Comment by letechi123** [comment]
Well technically speaking considering the performance of ASIC's, would you not have more of a chance by doing a random nonce, then incrementing by 1? Because an ASIC can exhaust the whole nonce space rather quick? Or am i missing something & getting confused?

**Comment by letechi123** [comment]
so instead of starting at nonce 0, you can randomly just throw out nonces, and might get a random hit, like i said i might be confusing something or my understanding is not correct, so i figured who better to ask then the person behind the project

**Comment by pooler** [comment]
> would you not have more of a chance by doing a random nonce, then incrementing by 1?

No, every value has the same probability of being a solution, and altering the order in which nonces are checked does not increase the probability of finding one. However, generating random numbers would be slower than just incrementing the nonce.

**Comment by letechi123** [comment]
out of curiosity considering you are always starting at nonce 0, does it not mean that someone using an ASIC miner would clear that same nonce space, and you are pointlessly going over it, where others have already been ? or does every miner have some sort of randomness attached to there mining process compared to others which keeps it unique ?

**Comment by pooler** [comment]
Every miner is given a different Merkle root, so there is no direct competition.

**Comment by letechi123** [comment]
ahh, that clarifies everything now, i figured everyone was using the same block header, and was a race to who actually finds the golden hash.. 

but now that i know everyone is given a different merkle it makes sense.. 

thank you very much pooler

**Comment by cculianu** [comment]
If every miner were given the same block header then they could cheat the pool by claiming shares were solved when they weren't.  You could connect 10000 fake workers and have 1 real worker find the solution and submit it 10,000 times.  Obviously this would break the payouts.

So each worker is necessarily given a unique coinbase transaction, which creates  a unique merkle to solve.
