### ISSUE TITLE
How i can dissplay ( debug nonce and blocks?)

### ISSUE THREAD

**Issue by mraksoll4** [pooler/cpuminer#195]
How i can display at debug current nonce/rawblock data ?)
where add code ?
and how i can make fixed / randome nonce ? where need add changes ? ( i cannot find line of code where is create and input nonce )

**Comment by pooler** [comment]
This is an issue tracker, not a help forum. Closing.

**Comment by mraksoll4** [comment]
This is issue , i cannot see debug info of nonce etc )

**Comment by pooler** [comment]
All submitted information, including nonces, is printed if you enable the protocol dump (`-P`).

**Comment by mraksoll4** [comment]
Its print only rpc protocol info :(  get an and push requst of rpc )
but  need debug miner variable before nonce is add to block header and rolled at algo , and result before it try submitblockhash , and submitblock. And maybe slow down hashrate for see it per-hash work. 

the code is litle confus me. Sorry if i waste your time , i simple try use debuger .
