### ISSUE TITLE
Cookie based authentication

### ISSUE THREAD

**Issue by liorko87** [pooler/cpuminer#208]
Hello,

I'm trying to use the cpu miner with Cookie based authentication.

At my `bitcoin.conf` the following line appear:
`rpcauth=myuser:mypassword`

When I'm trying to mine using this command: `./minerd --url=http://url:port --userpass=myuser:mypassword --coinbase-addr=address --threads=4`, I received this error: `HTTP request failed: The requested URL returned error: 401`

Also at the bitcoin debug log, this line appear: `ThreadRPCServer incorrect password attempt from url:port`.

How can I mine my blocks using cookie based authentication?

**Comment by pooler** [comment]
In `bitcoin.conf`, `rpcauth` takes a hashed password. See the documentation for `rpcauth`; helper scripts are available in the Bitcoin repo.

**Comment by liorko87** [comment]
I totally understand that `rpcauth` uses a hashed and salted password. My question is how to use `cpuminer` with the cookie based authentication? which parameter should I pass to the executable in order to a successful authentication?

**Comment by liorko87** [comment]
Thank you for your answer.
The username and password are located in `.cookie` in the data directory of the bitcoin executable.
