### ISSUE TITLE
100% rejection

### ISSUE THREAD

**Issue by spk48** [pooler/cpuminer#210]
I run the program with
`./minerd  -o stratum+tcp://sz.ss.btc.com:1800 -u 8Vn8h0GwG0PM4S.001 &`
**But I get 100% rejection for 10 hours running.**
I think there must be something wrong.
PS, I also test a **different machine on a different pool,** also get the **same result** "**100% rejection**".
Could you please give me some advice?

**Comment by pooler** [comment]
You are probably not using the right hashing algorithm for what you are trying to mine. See the `-a` option.
