### ISSUE TITLE
how to solomine

### ISSUE THREAD

**Issue by DumbGameMaker** [pooler/cpuminer#216]
i am trying to solomine LTC but when I try it asks for a URL. What should I put the URL as? localhost? my command is this
`./minerd -a scrypt --coinbase-addr=LTLke7G9PJftfhGZbddbkWcSHeGiSnWAMc`
that is not a coinbase address, it is the address of my local wallet, but i didnt see an option for `--wallet-addr`

**Comment by pooler** [comment]
You will need to pass the address of your mining server (whether local or not) using the `-o` option. For instance it could be something like `-o http://localhost:9332`.

This is not a support forum, closing.
