### ISSUE TITLE
cpuminer / minerd application doesn't start

### ISSUE THREAD

**Issue by Cookee42** [pooler/cpuminer#221]
Hello,

I am posting on this forum because I would like to try dogecoin mining.
So I download the full dogecoin wallet as well as cpuminer.
Once the software is downloaded and unzipped, I go to launch the minerd application.
But, at that point, nothing happens when I double-click on minerd.
I thought about launching it in administrator mode, but the option does not appear.

Do you have a solution please?

Thank you.

**Comment by pooler** [comment]
cpuminer is a console application, it does not have a graphical interface.

This is an issue tracker, not a support forum. Closing ticket as invalid.
