### ISSUE TITLE
How to get block header of Bitcoin ?

### ISSUE THREAD

**Issue by Kiarash2473** [pooler/cpuminer#222]
I am new to the concepts of mining Bitcoin .
I am trying to use my unique nonce in block header and submit it for proof of work , but I do not know where to put the nonce in cpuminer program and submit it .
I also need to know how to get the other components of the block header and put them together .

**Comment by pooler** [comment]
Sorry but you're in wrong place. This is an issue tracker, not a forum for general discussion. I suggest you try asking on Bitcointalk.
