### ISSUE TITLE
HTTP request failed: Can't complete SOCKS5 connection to 127.0.0.1. (1)

### ISSUE THREAD

**Issue by cgunnels** [pooler/cpuminer#224]
I'm running this command yet I get this http error:
`./minerd -a sha256d -O user:pass --coinbase-addr=xyzxxxxxxxxx -t 2 -o 127.0.0.1:9050 -x socks5://127.0.0.1:9050`

**Comment by pooler** [comment]
It seems highly unlikely that `-o 127.0.0.1:9050` is what you want. The `-o` flag takes the address of the mining server, and `127.0.0.1:9050` is usually the address of a Tor proxy.

Closing ticket, since this is not a help forum.

**Comment by cgunnels** [comment]
thanks for the reply. I'm mining on my local machine and I have the full node setup on my local machine and my bitcoin.conf file contains 
```
# Node will only route through Tor network. Important for Privacy.
onion=127.0.0.1:9050
listenonion=1
onlynet=onion
proxy=127.0.0.1:9050
proxyrandomize=1
```
I'm running tor as well.
