### ISSUE TITLE
cpuminer autocloses after opening in cmd

### ISSUE THREAD

**Issue by ReconLTU** [pooler/cpuminer#229]
cpuminer autocloses after opening in cmd

OS:Windows 10 pro. 

Any solution ?

**Comment by ReconLTU** [comment]
Tryed opening via cmd on other computer who also windows 10 pro its autocloses program same as on my main one

**Comment by pooler** [comment]
`minerd` is supposed to exit immediately (after printing an error message) if you don't pass any parameters.

**Comment by pooler** [comment]
Is the error message not getting printed to the console?

**Comment by ReconLTU** [comment]
No error message. Just opens and closes window in second.

**Comment by pooler** [comment]
You mentioned `cmd`, but how exactly are you running `minerd`? Feel free to attach a screenshot.

**Comment by StalkerLegend** [comment]
Hello. I have a problem too auto-close. 
Screenshot: https://ibb.co/yydJ8pj

**Comment by pooler** [comment]
@StalkerLegend, you are starting `minerd` from within a batch file and passing an option that doesn't exist (`--scrypt`). It's expected behavior for `minerd` to quit. If you run it from a command prompt, you will also see an error message.

**Comment by StalkerLegend** [comment]
Help me please. What command should I specify? To mine Litecoin / Dogecoin

**Comment by pooler** [comment]
@StalkerLegend, this is an issue tracker, not a support forum. You can ask such questions on BitcoinTalk or similar venues.

**Comment by pooler** [comment]
No response from OP, and cannot reproduce. Closing.
