### ISSUE TITLE
trying --url= (or -o) just prints help message

### ISSUE THREAD

**Issue by skinny-pete** [pooler/cpuminer#231]
hi,
any attempt to use --url or -o and entering a URL prints "Try `minerd --help' for more information", as if the syntax was wrong. Built on ubuntu 22.04, no build errors. To prevent confusion, this is the command I use to attempt to start it:
./minerd --url=stratum+tcp://ltc-eu.f2pool.com:8888 --userpass=workerid:password
obviously replacing workerid:password with the real credentials. I have tried every variant you can imagine including copy pasted from known-working forum posts and documentations, every time I try to use the --url or -o option, it prints the 'try minerd --help' string

**Comment by pooler** [comment]
>  ./minerd --url=stratum+tcp://ltc-eu.f2pool.com:8888 --userpass=workerid:password

I'm unable to reproduce. The command you provided gives me no error at all, and the miner starts as expected. Are you adding any other options by any chance? I just glanced at the code, and unless I'm missing something, if you're not passing any other options it doesn't seem possible that the miner doesn't give a more specific error message.

**Comment by skinny-pete** [comment]
No nothing else, and like I said I've tried -o, --url and some other syntaxes I found on forums, but same result every time
![cpuminer](https://user-images.githubusercontent.com/52208431/118355697-404e5100-b569-11eb-968b-322ec4033273.png)

(I've tried this with the real credentials of course too)

**Comment by pooler** [comment]
I was assuming you were using a recent version, but I see it's actually version 2.2.3, which is from 2012. Stratum support was introduced in version 2.3, so it's only normal that it's not working.

**Comment by skinny-pete** [comment]
my apologies, I must have been copying the git clone from an old forum post, thank you for your time.
