### ISSUE TITLE
error ./configure no such file or directory

### ISSUE THREAD

**Issue by imtrynalearn** [pooler/cpuminer#234]
while compiling on msys windows

**Comment by pooler** [comment]
Assuming you're trying to build cpuminer, you'll have to provide more information on what steps you've followed.

**Comment by imtrynalearn** [comment]
after ./configure got this error

```
./configure: line 5560: syntax error near unexpected token `,'
./configure: line 5560: `LIBCURL_CHECK_CONFIG(, 7.15.2, ,'
```

**Comment by pooler** [comment]
Duplicate of #37. You'll need a full libcurl development package to build from the git repo. Alternatively, build from tarball.
