### ISSUE TITLE
my libcurl version is >= 7.15.2 but its still error.

### ISSUE THREAD

**Issue by imtrynalearn** [pooler/cpuminer#235]
```
checking for curl-config... /mingw/bin/curl-config
checking for the version of libcurl... 7.30.0
checking for libcurl >= version 7.15.2... yes
checking whether libcurl is usable... no
configure: error: Missing required libcurl >= 7.15.2
```

**Comment by pooler** [comment]
Please provide `config.log`. Also, are you building from the git repo or from tarball?

**Comment by pooler** [comment]
Please provide `config.log`. Also, are you building from the git repo or from tarball?

**Comment by imtrynalearn** [comment]
[config.log](https://github.com/pooler/cpuminer/files/6583707/config.log)

**Comment by imtrynalearn** [comment]
I builded using msys on windows

**Comment by pooler** [comment]
> c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lcurldll

There's your problem. Make sure that you have the proper libraries installed and that the build system knows where to find them.

**Comment by imtrynalearn** [comment]
where should I put my libraries
when I installed libcurl i used ./configure –prefix=/c/mingw 
make
make install

**Comment by pooler** [comment]
I don't know much about MSYS, but generally speaking you can put your libraries wherever you want. You might just have to tell `configure` where to find them.

**Comment by imtrynalearn** [comment]
What is the command order to do that?

**Comment by pooler** [comment]
You would normally set `LDFLAGS` to tell the linker where to find your libraries. This is nothing specific to cpuminer.

Sorry but this is an issue tracker, not a help forum. I'm seeing no indication of a cpuminer issue, so I'm closing this ticket.

**Comment by imtrynalearn** [comment]
this command `CFLAGS="-O2 -msse2" ./configure` works, this `LIBCURL="-lcurldll" ./configure CFLAGS="-O3"` not. Do you have a clue why?

**Comment by pooler** [comment]
My guess would be that you have the `curl` library file installed but not the `curldll` one.

**Comment by imtrynalearn** [comment]
why does it have tons of malwares https://www.virustotal.com/gui/file/7d4dc9c9456054b8c655b382356ee46332911d64375ab6af3e6910632e1226aa/detection

**Comment by imtrynalearn** [comment]
anyways do you know how to fix this error while I build sgminer 
```
In file included from sgminer.c:52:0:
compat.h:76:19: error: conflicting types for 'sleep'
 static inline int sleep(unsigned int secs)
                   ^~~~~
In file included from sgminer.c:24:0:
c:\mingw\include\unistd.h:117:10: note: previous definition of 'sleep' was here
 unsigned sleep( unsigned period ){ return __mingw_sleep( period, 0 ); }
```
