### ISSUE TITLE
Can't compile at openbsd 6.9

### ISSUE THREAD

**Issue by MateuszCz** [pooler/cpuminer#241]
Hi,
I'm trying to compile git;
https://pastebin.pl/view/f6ec0491
[I found this ](https://gnu.emacs.bug.narkive.com/uRiolRik/bug-42860-28-0-50-build-on-openbsd-fails-in-jansson-h)

**Comment by pooler** [comment]
Just tried on a fresh OpenBSD 6.9 install, I had no problem building from the cpuminer 2.5.1 tarball.
I was able to reproduce your issue after installing the `jansson` package. As the link you posted points out, it appears to be a versioning issue. I resolved it by installing the `gcc` package (which got gcc 8.4.0 installed as `egcc` alongside gcc 4.2.1) and passing `CC=egcc` to `configure`.
