### ISSUE TITLE
Solo Miner is not running

### ISSUE THREAD

**Issue by smileysuresh** [pooler/cpuminer#244]
` HTTP request failed: The requested URL returned error: 401`

git clone https://github.com/pooler/cpuminer.git

can anyone help how to resolve this

**Comment by pooler** [comment]
Sorry, you're in the wrong place. This is the issue tracker for cpuminer, not a forum.

**Comment by smileysuresh** [comment]
Hi, I have posted the query related to cpuminer only. (git clone https://github.com/pooler/cpuminer.git). I got an error to run the cpuminer. Please check once again the query i have raised

**Comment by pooler** [comment]
This tracker is meant for bugs in cpuminer, not for helping users. Moreover, the error you posted (most probably an authentication error) was produced by the server, not by cpuminer.

**Comment by smileysuresh** [comment]
can you please help me out, how to solve the problem, i am using amazon aws ec2 instance. Please...

**Comment by pooler** [comment]
> can you please help me out, how to solve the problem, i am using amazon aws ec2 instance. Please...

You should try asking for help on BitcoinTalk or similar forums.
