### ISSUE TITLE
getting debug false positive flag

### ISSUE THREAD

**Issue by sachinverma1** [pooler/cpuminer#255]
hi,

i am mining solo to litecoin with cpu pooler

and getting this message :-

DEBUG: hash > target (false positive)
Hash:	00000000194f58313866fccddf17fda95b6ec6441e86e8e510cb026cbb50c769
Target: 00000000000001320b0000000000000000000000000000000000000000000000

can anyone help to understand what is this message for?

is it something wrong with the miner or with my RPC file?

**Comment by pooler** [comment]
It's normal. For performance reasons cpuminer only computes the first 32 bits of a hash, and if they show potential for a solution it goes on to compute the full hash. If the full hash does not meet the target, it's reported in debug mode as a false positive.

> Hash: 00000000194f58313866fccddf17fda95b6ec6441e86e8e510cb026cbb50c769
> Target: 00000000000001320b0000000000000000000000000000000000000000000000

The target here is quite low (or in other words, the difficulty is quite high) for a CPU miner, so you will get many false positives in the sense described above.

**Comment by sachinverma1** [comment]
Thank you for your response.

I got the point what you said...

So here, can you please help me that how to lower this false positive
response?

**Comment by pooler** [comment]
> So here, can you please help me that how to lower this false positive response?

Simply turn off debug mode.

**Comment by sachinverma1** [comment]
Then how I will see blocks accepted, if it comes...

And if I off debug mode will that effect to reduce this false positive or
orphan block...? Or it will just hide for me but internally it will do the
same?

**Comment by pooler** [comment]
> Then how I will see blocks accepted, if it comes...

The miner reports accepted/rejected solutions by default, no need for debug mode. That said, you probably won't see many solutions (if any at all) because that difficulty is high for a CPU miner.

> And if I off debug mode will that effect to reduce this false positive or orphan block...? Or it will just hide for me but internally it will do the same?

As explained above, this kind of false positive is not a bad thing, and definitely not something you need to worry about. And orphan blocks are totally unrelated.

**Comment by sachinverma1** [comment]
Oh.. OK. Great.. Thank you... Means I don't need to worry about that at
all.....

Thank you my friend.

**Comment by sachinverma1** [comment]
Do you know any gpu miner for scrypt Algo... Which supports GBT protocol
and solo mining?

**Comment by pooler** [comment]
Sorry, this is not the best place to ask. You may want to try Reddit or a mining forum.
