### ISSUE TITLE
accepted: 0/1 (diff 0.000), 8.91 H/s booooo

### ISSUE THREAD

**Issue by CalRFitz** [pooler/cpuminer#262]
Does anybody have any idea how I can fix this? I have been mining on a rasp pi in case you are wondering why my hash rate is so low, but i've been using the cryptonight algorithim and mining monero and I still can't find out whats going on. If anybody can help, please let me know.

**Comment by pooler** [comment]
That output is not from the program in this repo. Please direct your questions to the maintainers of the relevant fork.
