### ISSUE TITLE
Syntax error on line 4024 of the configure file.

### ISSUE THREAD

**Issue by amritabithi** [pooler/cpuminer#275]
I am encountering the following syntax error when running the ./configure script and it is preventing me from building, I have tried on Ubuntu 20.04.5 and MX Linux with the same results.  

The error appears to me to be a mis-typed comment opening sequence where the escape slash for the quote has combined for form a comment closure.

Here i s a screenshot of the error on line 4024:

![image](https://github.com/pooler/cpuminer/assets/48937881/9cec4abe-7d3f-49de-80da-1c49aad80a21)

**Comment by pooler** [comment]
I'm assuming you are building from the git repo, as the `configure` file in the official tarball of v2.5.1 differs from the version above. It probably depends on the version of Autoconf you're using and on your general setup. For what it's worth, I just trying building on Arch with Autoconf 2.71 and everything seems to work fine.

**Comment by amritabithi** [comment]
Closed as duplicate.
