### ISSUE TITLE
Does cpuminer work for BTC?

### ISSUE THREAD

**Issue by shanhashcah** [pooler/cpuminer#276]
Hi @pooler Sir:

Actually I want to test mining for BTC so I have run cpuminer and connected  with a pool. But no share has accepted now. Of course we need ASIC miner for BTC but I want to test nothing more **but  cpuminer works for LTC which I tested**. That is why I am thinking that cpuminer can be worked for BTC.

Many Thanks!

**Comment by pooler** [comment]
It works in the sense that it is implemented correctly, but in practice a CPU is now too slow to realistically find even a single share at a Bitcoin pool.

**Comment by shanhashcah** [comment]
ok @pooler Sir, Thanks for your quickest reply.
