### ISSUE TITLE
clang: error: no such file or directory: '@LIBCURL_CPPFLAGS@'

### ISSUE THREAD

**Issue by Hamtar0z** [pooler/cpuminer#278]
Basic *nix build instructions:
	./autogen.sh	# only needed if building from git repo
	./nomacro.pl	# in case the assembler doesn't support macros
	./configure CFLAGS="-O3" # make sure -O3 is an O and not a zero!
	make

clang: error: no such file or directory: '@LIBCURL_CPPFLAGS@'

**Comment by pooler** [comment]
You probably didn't have the required libcurl development package installed.

Try building from tarball instead.

**Comment by Hamtar0z** [comment]
> You probably didn't have the required libcurl development package installed.
> 
> Try building from tarball instead.
<img width="1118" alt="Screen Shot 2567-04-10 at 17 11 30" src="https://github.com/pooler/cpuminer/assets/166582787/6c94a188-41f8-4464-bf23-02110120527f">

error same as before

**Comment by Hamtar0z** [comment]
..

**Comment by pooler** [comment]
> > Try building from tarball instead.
> 
> error same as before

Did you use `pooler-cpuminer-2.5.1.tar.gz` from https://github.com/pooler/cpuminer/releases?

**Comment by Hamtar0z** [comment]
> > > Try building from tarball instead.
> > 
> > 
> > error same as before
> 
> Did you use `pooler-cpuminer-2.5.1.tar.gz` from https://github.com/pooler/cpuminer/releases?

git clone https://github.com/pooler/cpuminer.git

**Comment by Hamtar0z** [comment]
> > > Try building from tarball instead.
> > 
> > 
> > error same as before
> 
> Did you use `pooler-cpuminer-2.5.1.tar.gz` from https://github.com/pooler/cpuminer/releases?

how to start in mac os
