### ISSUE TITLE
local mining pool collisions

### ISSUE THREAD

**Issue by klim9929** [pooler/cpuminer#289]
I have several unused devices at home and I made a local mining pool out of them. On one I synchronized the blockchain in bitcoin core and I connect the rest over the local network. Can I be sure that my devices are not going through the same nonce at the same time depending on their hash rate? How is the initial nonce selected in this program.

I apologize for my English, I used a translator

**Comment by pooler** [comment]
Giving different work to different clients (by varying the Merkle root hash) is the server's responsibility. All supported protocols allow clients to use the whole nonce space.
