### ISSUE TITLE
syntax error when running ./configure, LIBCURL_CHECK_CONFIG

### ISSUE THREAD

**Issue by ghost** [pooler/cpuminer#37]
I'm using Linux Mint and I have libcurl3 installed. When I run `./configure CFLAGS="-O3"` it gives me the following error:

```
checking whether we can compile AVX code... yes
checking whether we can compile XOP code... yes
checking whether we can compile AVX2 code... yes
checking for json_loads in -ljansson... no
checking for pthread_create in -lpthread... yes
./configure: line 5542: syntax error near unexpected token `,'
./configure: line 5542: `LIBCURL_CHECK_CONFIG(, 7.15.2, ,'
```

I think `autogen.sh` gave me a warning but I'm not sure if it's related to this.

**Comment by gaffelosked** [comment]
Can't install libcurl via yum install on centos fml

**Comment by given13** [comment]
okay so I got this far I am compiling under mingw on windows. I ran autogen.sh then LIBCURL="-lcurldll" ./configure CFLAGS="-O3". and I get this error. I installed libcurl 7.57.0 per winbuild instructions. I copied the bin,include, and lib directories from the C:\curl-7.57.0\builds\libcurl-vc-x86-release-dll-ipv6-sspi-winssl dir in curl to mingw bin include and lib folder. This thread says to install libcurl4-openssl-dev but I do not see that as an option for windows. how do I get this working? help is greatly appreciated!!

**Comment by liorko87** [comment]
You should add this to the INSTALL.md/README.md file for ubuntu.

**Comment by artemYashin** [comment]
<img width="529" alt="image" src="https://user-images.githubusercontent.com/23138285/152254551-7f75341e-49ed-43a7-8f37-0ab0380431a4.png">

**Comment by brandonros** [comment]
![image](https://github.com/pooler/cpuminer/assets/8949910/d879ce60-a810-4815-b05d-905a0c78dfa5)

```shell
brew install curl autoconf automake pkg-config
export LDFLAGS="-L/opt/homebrew/opt/curl/lib"
export CPPFLAGS="-I/opt/homebrew/opt/curl/include"
export CFLAGS="-I/opt/homebrew/opt/curl/include -lcurl"
export PKG_CONFIG_PATH="/opt/homebrew/opt/curl/lib/pkgconfig"
```

2024 MacOS Apple Silicon workaround seems to work

**Comment by bitnet-io** [comment]
> ```shell
> export LDFLAGS="-L/opt/homebrew/opt/curl/lib"
> export CPPFLAGS="-I/opt/homebrew/opt/curl/include"
> export CFLAGS="-I/opt/homebrew/opt/curl/include -lcurl"
> export PKG_CONFIG_PATH="/opt/homebrew/opt/curl/lib/pkgconfig"
> ```

what are the export flags to build the minerd.a for iOS target instead of macOS target ?
how can i actually build minerd.a static lib for iOS ?

i used this script to try and build iOS libs

https://github.com/bitnet-io/Build-OpenSSL-cURL-for-iOS
