### ISSUE TITLE
Support for scrypt-jane

### ISSUE THREAD

**Issue by fabulouspanda** [pooler/cpuminer#56]
Thanks for your cpuminer pooler, I can compile and use it in MacMiner fine, but I'm having no luck with this:
https://github.com/Thirtybird/cpuminer

due to the macros around scrypt-jane-portable-x86.h

I'd much appreciate it if you'd take a look at integrating support in your cpuminer!

**Comment by pooler** [comment]
Closing as there are currently no plans to add support for more algorithms.
