### ISSUE TITLE
doesn't work with bitcoin block version 3

### ISSUE THREAD

**Issue by y** [pooler/cpuminer#89]
I'm using the latest git version of bitcoind and it only uses blocks version 3 [1], and cpuminer won't work unless I change BLOCK_VERSION_CURRENT in cpu-miner.c from 2 to 3.

[1] https://bitcoin.org/en/developer-reference#block-versions

**Comment by pooler** [comment]
Thank you for pointing this out. Since version 3 introduces no changes that concern cpuminer, bumping BLOCK_VERSION_CURRENT is all there is to do.

Fixed in 07fb67e.
