### ISSUE TITLE
not compile with autogen.sh

### ISSUE THREAD

**Issue by WHK102** [pooler/cpuminer#91]
me@me:~/cpuminer-master$ ./autogen.sh 
configure.ac:13: installing './compile'
configure.ac:4: installing './config.guess'
configure.ac:4: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am:12: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
Makefile.am: installing './INSTALL'
Makefile.am: installing './depcomp'
configure.ac:124: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
me@me:~/cpuminer-master$

**Comment by pooler** [comment]
Possible duplicate of #74. Please make sure the development package for libcurl is installed.

**Comment by WHK102** [comment]
The installation of this library ubuntu depends on a downgrade of many other libraries including openssl and in doing so the team not only outdated but is totally vulnerable to Heartbleed. One solution would be the application include their own versions of libraries and compile completely in the / opt not to affect the normal performance of the computer or use updated system software current versions.

In Windows I have no problems, double click on the executable and ready is made, but in ubuntu I had a sea of troubles, just say that all installation manuals I've seen online include messages like "if an error occurs to install, it's normal. "

**Comment by pooler** [comment]
libcurl is a dependency, so you'll have to get it in one way or another if you want to build cpuminer. If your package manager is giving you a headache, you can always compile libcurl from source.

> In Windows I have no problems, double click on the executable and ready is made, but in ubuntu I had a sea of troubles

Is there any particular reason why you don't want to use the official Linux binaries?

**Comment by WHK102** [comment]
That are available for binary cgminer not to cpuminer. I need CPUMiner not CGMiner. You're right, just checked it's a bug of ubuntu and a repository, while not resolved I'll be unable to compile.

**Comment by pooler** [comment]
I am talking about cpuminer.
https://bitcointalk.org/index.php?topic=55038
https://sourceforge.net/projects/cpuminer/files/

**Comment by alsternerd** [comment]
It's offline, pooler.
> FYI, you can find binaries for Linux, OS X, and Windows here:
> https://sourceforge.net/projects/cpuminer/files/

**Comment by alsternerd** [comment]
Since Sourceforge is down for now, here's the github URL:
https://github.com/pooler/cpuminer/downloads

**Comment by phr34k0** [comment]
`apt-get install libcurl4-openssl-dev` .. Long winded just to solve a simple issue. >_>
