### ISSUE TITLE
Cannot mine UTC

### ISSUE THREAD

**Issue by IMweasel** [pooler/cpuminer#92]
Hello Pooler,
I recently began mining UTC,which is a Scrypt-N coin.
At first i was using a Ccminer fork,which was based on a Lucas Jones fork,compiled by tpruvot.
(cpuminer-multi v1.0.9 (Linux + Windows)
There were only boo's for days straight,and i could not get it any better.
I figured it might be a coding error,so i tried your 'original' miner for the job.
There were a lot less boo's now,but still only boo's...i felt like the few boo's should have been yays...
And i can't figure out why!
I now tried out Yacminer and what do you know...yay!
The only thing i'm doing different is using the nfmin/nfmax/starttime flags. Are these mandatory to successfully mine this coin?
So i went from; 
"minerd" -a scrypt:131072 -O x:x -o 127.0.0.1:44101 -s 1 -R 1 -T 1
to
"minerd-x64-avx" -a scrypt-chacha --nfmin=4 --nfmax=30 --starttime=1388361600 -O x:x -o 127.0.0.1:44101 -s 1 -R 1 -T 1
I really wonder if your own miner can do the job natively? Would love to have these fabulous Mingw speeds back! Thanks!

**Comment by pooler** [comment]
UltraCoin uses the scrypt-chacha algorithm, which is a variant of scrypt sporting a different inner loop.
It is not supported by this cpuminer, sorry.

**Comment by IMweasel** [comment]
Alright,i figured it was something like that.. thanks!
