### ISSUE TITLE
Stratum keeps requesting work restart

### ISSUE THREAD

**Issue by colt05** [pooler/cpuminer#95]
Hey guys, I have been mining for bitcoins on Slush's Pool (stratum+tcp://stratum.bitcoin.cz:3333) and cpuminer is running on a Koding VM. I keep getting "Stratum requested work restart" but then I get this:
thread 0: 257818480 hashes, 8591 khash/s
DEBUG: hash > target (false positive)
Hash:   0000000050ea2b0ac608b30d08178e7b13d21e13a47f12d6ebd6a253466ef777
Target: 000000001fffe000000000000000000000000000000000000000000000000000
DEBUG: hash > target (false positive)
Hash:   00000000484c19edc82403e1a83b785ddb210c653f4d00e8b05336a370960acf
Target: 000000001fffe000000000000000000000000000000000000000000000000000
I never got this far on TomPool multipool (I am using Slush's pool now though which tells me my worker is offline), so is there a fix for the work restart? Thanks.

**Comment by pooler** [comment]
A few work restarts per minute are totally normal. Besides, it's the server that decides when the client should start working on a new job, and there's nothing you can do about that.
False positives are also totally normal when the share difficulty is higher than 1. (Your examples show a difficulty of 8).

**Comment by colt05** [comment]
Thanks! But sometimes, it says "Stratum requested work restart" after every time it says something like "thread 0: 257818480 hashes, 8591 khash/s."

**Comment by pooler** [comment]
That is also normal. When switching jobs the number of computed hashes and the speed are printed (unless quiet mode is enabled).

**Comment by colt05** [comment]
Oh, is that so? Thanks for the information.

**Comment by reppolice** [comment]
Hmm, doesn't that "switching jobs" mean the work has been lost, since only "shares yay" count?

**Comment by pooler** [comment]
@reppolice No, it doesn't. Mining is a memoryless process, there is no "progress" that you can lose.

**Comment by sunk818** [comment]
Is there a delay when you are "switching jobs". Meaning the miner is not hashing when it stops mining for the last block (because it has been solved) and is waiting for the next block from the pool server? This is pretty quick I imagine?

**Comment by Lucas1749** [comment]
[2024-12-01 23:07:59] accepted: 15667/15961 (98.16%), 23236 khash/s (booooo)
Oque significa esse (booooo) ?

**Comment by dorothymesservey78-hue** [comment]
> A few work restarts per minute are totally normal. Besides, it's the server that decides when the client should start working on a new job, and there's nothing you can do about that. False positives are also totally normal when the share difficulty is higher than 1. (Your examples show a difficulty of 8).

so the miner doesn't adhere to the pools set difficulty? just sends out any hash with a diff higher then one ?
