### ISSUE TITLE
stratum+tcp:// Syntax Error

### ISSUE THREAD

**Issue by haris00** [pooler/cpuminer#96]
I am on ubuntu 15.04 Server. 
If I use 
./minerd -o stratum+tcp://us2.litecoinpool.org:3333 --user USER --pass PASS
it throws out :

Try `minerd --help' for more information.

And If use 
./minerd -o stratum+tcp:/us2.litecoinpool.org:3333 --user USER --pass PASS
OR
./minerd -o stratum+tcp:us2.litecoinpool.org:3333 --user USER --pass PASS
It starts fine but the url is now incorrect and it cannot connect

**Comment by pooler** [comment]
I cannot reproduce this. I tried the exact command line you posted,
```
./minerd -o stratum+tcp://us2.litecoinpool.org:3333 --user USER --pass PASS
```
and it worked just fine with the latest version.

**Comment by haris00** [comment]
I got this error on version 2.3 but i guess its fixed in version 2.4

**Comment by pooler** [comment]
I just tried with version 2.3 and I still can't reproduce it. Are you 100% sure that the command line you used is exactly what you posted above?

**Comment by haris00** [comment]
I am very sorry
It was version : 2.2.3 
Here is the link
https://github.com/downloads/pooler/cpuminer/pooler-cpuminer-2.2.3.tar.gz

**Comment by pooler** [comment]
Now that makes sense. Support for the Stratum protocol was only added in version 2.3.
By the way, version 2.2.3 is over 3 years old, you should definitely upgrade. See the [changelog](https://github.com/pooler/cpuminer/blob/master/NEWS) for more information.

**Comment by haris00** [comment]
Yea I had already upgraded to version 2.4, but just wanted to let you guys know
Thanks for the help
