### ISSUE TITLE
LibcURL problem.

### ISSUE THREAD

**Issue by colt05** [pooler/cpuminer#98]
Hi.
I have been having a problem with cURL when trying to build a fork of cpuminer.
Error:
./configure: line 5659: `LIBCURL_CHECK_CONFIG(, 7.15.2, ,'
Is there a fix for this?
Thanks!

**Comment by colt05** [comment]
I also tried installing libcurl4-gnutls-dev.

**Comment by pooler** [comment]
Duplicate of #37.
