### ISSUE TITLE
called object is not a function or function pointer

### ISSUE THREAD

**Issue by colt05** [pooler/cpuminer#99]
Hi.
I got two errors when building.
ERROR:
cpu-miner.c: In function 'miner_thread':
cpu-miner.c:1191:32: error: called object is not a function or function pointer
   rc = algo_scanhash[opt_algo] (thr_id, work.data, algo_thread_local_data, work.target, 
                                ^
cpu-miner.c:1191:6: warning: assignment makes integer from pointer without a cast [enabled by default]
   rc = algo_scanhash[opt_algo] (thr_id, work.data, algo_thread_local_data, work.target, 
      ^

Is there a missing semicolon that the compiler is not showing? Thanks.

**Comment by pooler** [comment]
I don't see the symbol `algo_scanhash` anywhere in cpu-miner.c.
Please use the latest source from this repository.

**Comment by colt05** [comment]
Oh i guess it is a problem with the fork I am using...
